# Generated by Django 4.0.5 on 2022-08-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Downloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='video_size',
        ),
    ]
