# Generated by Django 4.0.5 on 2022-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Downloader', '0002_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField()),
                ('video_title', models.TextField()),
                ('video_description', models.TextField()),
                ('video_url', models.TextField()),
            ],
        ),
    ]
