# Generated by Django 4.0.5 on 2022-08-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Downloader', '0003_process_video_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
